# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0002_auto_20170712_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='kugou_is_tengxun',
            field=models.BooleanField(default=False),
        ),
    ]
