# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('head_url', models.CharField(max_length=200)),
                ('fans_num', models.BigIntegerField()),
                ('popular', models.BigIntegerField()),
                ('kugou_url', models.URLField(blank=True)),
                ('kugou_is_vip', models.BooleanField(default=False)),
                ('kugou_is_realname', models.BooleanField(default=False)),
                ('kugou_is_tao', models.BooleanField(default=False)),
                ('kugou_is_musician', models.BooleanField(default=False)),
                ('kugou_is_liver', models.BooleanField(default=False)),
                ('kugou_is_recommend', models.BooleanField(default=False)),
                ('kugou_is_star', models.BooleanField(default=False)),
                ('kugou_is_mobile', models.BooleanField(default=False)),
                ('kugou_is_xinlang', models.BooleanField(default=False)),
                ('kugou_is_renren', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('type', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('upload_time', models.DateTimeField()),
                ('lrc', models.TextField(max_length=500)),
                ('inspiration', models.TextField(max_length=1000)),
                ('song_popular', models.BigIntegerField()),
                ('song_click', models.BigIntegerField()),
                ('song_download_count', models.BigIntegerField()),
                ('song_collect', models.BigIntegerField()),
                ('song_like', models.BigIntegerField()),
                ('song_url', models.URLField()),
                ('arrange', models.ManyToManyField(blank=True, related_name='arrange', to='spiders.Author')),
                ('composer', models.ManyToManyField(blank=True, related_name='composer', to='spiders.Author')),
                ('lyricist', models.ManyToManyField(blank=True, related_name='lyricist', to='spiders.Author')),
                ('mixer', models.ManyToManyField(blank=True, related_name='mixer', to='spiders.Author')),
                ('original_singer', models.ManyToManyField(blank=True, related_name='original_singer', to='spiders.Author')),
                ('singer', models.ManyToManyField(blank=True, related_name='singer', to='spiders.Author')),
                ('style', models.ManyToManyField(to='spiders.Style')),
            ],
        ),
    ]
